version: "3.9"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - '3306:3306'
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql
volumes:
  db_data:
